---

## 📦 ReactNative / Schemas and flavors


### 🎓 Learn

- [CodePush](https://github.com/microsoft/react-native-code-push)

### 🎤 Interview

- Why we need to send source maps to Bugsnag?

### 📝 Katas

- Create an account on Bugsnag or FirebaseCrashlytics
- Setup an app with provided tool
- Show an error on a platform

---

## 📦 ReactNative / Brownfield app


### 🎓 Learn

- [CodePush](https://github.com/microsoft/react-native-code-push)

### 🎤 Interview

- Why we need to send source maps to Bugsnag?

### 📝 Katas

- Create an account on Bugsnag or FirebaseCrashlytics
- Setup an app with provided tool
- Show an error on a platform

---

## 📦 ReactNative / Advanced Offline Support


### 🎓 Learn

- [CodePush](https://github.com/microsoft/react-native-code-push)

### 🎤 Interview

- Why we need to send source maps to Bugsnag?

### 📝 Katas

- Create an account on Bugsnag or FirebaseCrashlytics
- Setup an app with provided tool
- Show an error on a platform

---
